# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CQYFqxKsTsuGiFAKE19btULhAyrm1Rle
"""

pip install BeautifulSoup4

import requests
from bs4 import BeautifulSoup
import pandas as pd

url='https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'
page=requests.get(url)
soup=BeautifulSoup(page.text,'html.parser')

article_title=soup.find(class_='mw-page-title-main').text
print(article_title)

companies_by_revenue=soup.find_all('table')[1]

world_titles=companies_by_revenue.find_all('th')
world_table_titles=[x.text.strip() for x in world_titles]

dframe=pd.DataFrame(columns=world_table_titles)

recored_data=companies_by_revenue.find_all('tr')

for i in recored_data[1:]:
    row_data=i.find_all('td')
    indiviual_row_data=[record.text.strip() for record in row_data]
    dframe.loc[len(dframe)]=indiviual_row_data

dframe.to_excel('List of largest companies in the United States by revenue.xlsx', index=False)



